api:
  addr: ":9410"
general:
  org_name: "Blog Microservice"
  website_base_url: "https://example.com"
transport:
  type: kafka
  kafka:
    urls:
      - kafka:9092
observability:
  otel_collector_addr: "otel-collector:4317"
channels:
  email:
    host: mailpit
    port: 1025
    from_addr: user@host
