api:
  addr: ":9410"
general:
  org_name: "Blog Microservices"
  website_base_url: "https://example.com"
transport:
  type: kafka
  kafka:
    urls:
      - localhost:9092
observability:
  otel_collector_addr: "otel-collector:4317"
channels:
  email:
    host: smtp.example.com
    port: 587
    username: myuser
    password: mypassword
    from_addr: myuser@example.com
