api:
  addr: ":9411"
  cors:
    allowed_origins:
      - "http://localhost:8081" # swagger ui
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "*"
transport:
  type: kafka
  kafka:
    urls:
      - localhost:9092
observability:
  otel_collector_addr: "otel-collector:4317"
storage:
  type: in_memory
auth:
  issuer: auth.example.com
  audience: blog-microservice
  public_key:
    type: file
    file: "/config/jwt.pub.pem"
